### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by webwayer** [webwayer/skills#72]
Поклацайте по сайту, и посмотрите лог браузера. А потом исправьте.

 Uncaught SyntaxError: Unexpected token <
sigma.canvas.edges.labels.def.js:1 Uncaught SyntaxError: Unexpected token <
sigma.canvas.edges.labels.curve.js:1 Uncaught SyntaxError: Unexpected token <
sigma.canvas.edges.labels.curvedArrow.js:1 Uncaught SyntaxError: Unexpected token <
angular.js:11594 TypeError: Cannot read property 'nodes' of undefined
    at Object.<anonymous> (http://localhost/bower_components/sigma/src/classes/sigma.classes.graph.js:703:10)
    at result [as read] (http://localhost/bower_components/sigma/src/classes/sigma.classes.graph.js:118:16)
    at Object.fn (http://localhost/front/app.js:52:29)
    at Scope.$digest (http://localhost/bower_components/angular/angular.js:14226:29)
    at Scope.$apply (http://localhost/bower_components/angular/angular.js:14489:24)
    at done (http://localhost/bower_components/angular/angular.js:9646:47)
    at completeRequest (http://localhost/bower_components/angular/angular.js:9836:7)
    at XMLHttpRequest.requestLoaded (http://localhost/bower_components/angular/angular.js:9777:9)
app.js:68 graph width: 100%
app.js:74 graph height: 500px
controllers.js:135 Object {leaves: Array[6], skills: Object, log: function, root: Object}
supervisor.js:165 Uncaught TypeError: Cannot set property 'x' of undefined

**Comment by VintorezVS** [comment]
Баги исправлены - тему закрыть.

**Comment by webwayer** [comment]
можешь закрыть сам :-)
